# ============================================================
# src/agent.py — ReconAI Core Agent
#
# This is the brain of ReconAI. It:
#   1. Takes a research topic from the user
#   2. Uses Tavily to search the live web
#   3. Passes the results to Claude for summarization
#   4. Returns a structured research report
#
# LangChain Concept: A "chain" is a sequence of steps.
# We use LCEL (LangChain Expression Language) with the | pipe
# operator to chain: prompt → LLM → output parser
# ============================================================

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from src.llm import get_llm
from src.search_tool import get_search_tool


# ── Prompt Template ───────────────────────────────────────
# This is the instruction we give Claude for every report.
# {topic} and {search_results} are placeholders filled in at runtime.
REPORT_PROMPT = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are ReconAI, an expert research assistant. 
Your job is to analyze web search results and produce clear, structured research reports.

Always follow this exact report format:

# Research Report: {topic}

## Executive Summary
(2-3 sentences summarizing the key finding)

## Key Findings
(5-7 bullet points of the most important facts)

## Detailed Analysis
(2-3 paragraphs expanding on the findings)

## Sources
(List each source URL from the search results)

---
*Report generated by ReconAI*

Be factual, concise, and cite sources where possible. 
If information seems outdated or conflicting, mention it."""
    ),
    (
        "human",
        """Research Topic: {topic}

Web Search Results:
{search_results}

Please generate a comprehensive research report based on these results."""
    )
])


def format_search_results(raw_results: list) -> str:
    """
    Converts Tavily's raw search results (list of dicts) into
    clean text that Claude can read and reference.

    Args:
        raw_results: List of result dicts from TavilySearchResults

    Returns:
        str: Formatted text with numbered sources
    """
    if not raw_results:
        return "No search results found."

    formatted = []
    for i, result in enumerate(raw_results, 1):
        # Extract fields safely (use .get() to avoid KeyError)
        title   = result.get("title", "Untitled")
        url     = result.get("url", "No URL")
        content = result.get("content", "No content available")

        formatted.append(
            f"[Source {i}] {title}\n"
            f"URL: {url}\n"
            f"Content: {content}\n"
        )

    return "\n".join(formatted)


def run_research(topic: str) -> dict:
    """
    Main function — runs the full ReconAI pipeline for a given topic.

    Pipeline:
        topic → web search → format results → Claude summarization → report

    Args:
        topic (str): The research topic entered by the user

    Returns:
        dict: {
            "topic":    the original topic,
            "report":   the generated markdown report (str),
            "sources":  list of source URLs found
        }
    """
    print(f"\n🔍 Searching the web for: '{topic}'...")

    # ── Step 1: Search the web ─────────────────────────────
    search_tool = get_search_tool()
    raw_results = search_tool.invoke(topic)

    # raw_results is a list of dicts like:
    # [{"title": "...", "url": "...", "content": "..."}, ...]
    print(f"   ✅ Found {len(raw_results)} sources")

    # ── Step 2: Format results for the LLM ─────────────────
    formatted_results = format_search_results(raw_results)

    # ── Step 3: Extract source URLs for the return value ───
    source_urls = [r.get("url", "") for r in raw_results if r.get("url")]

    # ── Step 4: Build the LangChain pipeline ───────────────
    # The | operator chains: prompt → llm → output_parser
    # StrOutputParser just extracts the text from Claude's response object
    llm = get_llm()
    chain = REPORT_PROMPT | llm | StrOutputParser()

    # ── Step 5: Run the chain ──────────────────────────────
    print(f"✍️  Claude is generating your report...")
    report = chain.invoke({
        "topic": topic,
        "search_results": formatted_results
    })

    print(f"   ✅ Report generated ({len(report)} characters)\n")

    return {
        "topic":   topic,
        "report":  report,
        "sources": source_urls
    }


# Quick test — run with: python -m src.agent
if __name__ == "__main__":
    result = run_research("quantum computing breakthroughs 2025")
    print(result["report"])